name: Deploy to Azure App Service
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-002-gen10-step3-2-node-oshima2
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT || 'https://app-002-gen10-step3-2-py-oshima2.azurewebsites.net' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Create deployment package
        shell: bash
        run: |
          set -euxo pipefail
          
          # Create deploy directory
          rm -rf deploy && mkdir -p deploy
          
          # Copy built application
          cp package.json deploy/package.json
          cp -R .next deploy/.next
          [ -d public ] && cp -R public deploy/public || true
          [ -f next.config.js ] && cp next.config.js deploy/next.config.js || true
          
          # Install production dependencies
          cd deploy
          npm ci --omit=dev
          
          echo "Deploy package created successfully"
          ls -la

      - name: Create artifact
        shell: bash
        run: |
          set -euxo pipefail
          (cd deploy && zip -qr ../artifact.zip .)
          ls -lh artifact.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: artifact.zip

      - name: Health check
        if: always()
        shell: bash
        run: |
          sleep 30
          APP_URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL" || echo 000)
          echo "HTTP $code"