name: build-and-deploy-mobile

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/build-and-deploy-mobile.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile
    env:
      NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: |
          echo "Building mobile with API base: $NEXT_PUBLIC_API_BASE"
          npm run build

      # ここは既存の Azure 静的デプロイ or App Service デプロイに合わせて差し替え。
      # 例：App Service deploy（Linux Node）
      - name: 'Azure WebApp Deploy (mobile)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.MOBILE_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.MOBILE_AZURE_PUBLISH_PROFILE }}
          package: apps/mobile/.next
