name: Deploy Mobile Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/deploy-mobile.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: |
          echo "Building mobile with API base: $NEXT_PUBLIC_API_BASE"
          npm run build
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.MOBILE_NEXT_PUBLIC_API_BASE }}

      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.MOBILE_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.MOBILE_AZURE_PUBLISH_PROFILE }}
          package: 'apps/mobile'